print("foodmate index")
print("this is the best food ")
print("foodmate is foodmatee")
print("changes in github")
print("new rebase")
print("product ")
print("new changes")
print("buy now")
print("squash")
print("again save")
print("3rd time again save")